In [17]:
import pandas as pd
import sqlite3
import plotly.express as px

In [1]:
db_path = r"db_repo/linguapy.db"

In [8]:
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# w_stat
cursor.execute("SELECT * FROM w_stat")
rows = cursor.fetchall()
column_names = [description[0] for description in cursor.description]
w_stat = pd.DataFrame(rows, columns=column_names)

# w_dictionary
cursor.execute("SELECT * FROM w_dictionary")
rows = cursor.fetchall()
column_names = [description[0] for description in cursor.description]
w_dictionary = pd.DataFrame(rows, columns=column_names)

# w_translated
cursor.execute("SELECT * FROM w_translated")
rows = cursor.fetchall()
column_names = [description[0] for description in cursor.description]
w_translated = pd.DataFrame(rows, columns=column_names)

In [11]:
w_stat.head(3)

     word_eng  count_learned
0   condition              1
1    indicate              1
2  connection              1

In [19]:
grouped_data = w_stat.groupby('count_learned')['word_eng'].count().reset_index()
grouped_data.rename(columns={'word_eng': 'word_count'}, inplace=True)

fig = px.bar(
    grouped_data,
    x='count_learned',
    y='word_count',
    title='Word Count by Count Learned',
    labels={'count_learned': 'Count Learned', 'word_count': 'Word Count'},
    text='word_count'  # Show values on the bars
)

fig.update_traces(textposition='outside')
fig.update_layout(
    xaxis=dict(title='Count Learned'),
    yaxis=dict(title='Word Count'),
    bargap=0.2
)

# Show the chart
fig.show()

In [12]:
w_dictionary.head()

,word_eng,definition,syns,antons,example
0,condition,the state of something with regard to its appe...,"state, shape, order, nick",,the wiring is in good condition
1,indicate,point out; show.,"designate, specify, stipulate, show",,dotted lines indicate the texts margins
2,connection,a relationship in which a person or thing is l...,"link, relationship, relation, relatedness, int...",,the connections between social attitudes and p...
3,violates,break or fail to comply with (a rule or formal...,"contravene, breach, commit a breach of, infrin...",comply with,they violated the terms of a ceasefire
4,consider,"think carefully about (something), typically b...","think about, contemplate, give thought to, ref...",,each application is considered on its merits

In [13]:
w_translated.head(3)

,word_eng,word_rus,word_rus_ext,time_added
0,condition,состояние,"condition , state , status , position , state ...",2021-12-29 10:16:04
1,indicate,указывать,"указывать на, обозначатьука́зывать , пока́зыва...",2021-12-29 13:59:18
2,connection,связь,"связь, подключение, соединение, пересадкасоеди...",2021-12-29 14:02:43

In [18]:
w_translated['time_added'] = pd.to_datetime(w_translated['time_added'])
daily_counts = w_translated.groupby(w_translated['time_added'].dt.date).size().reset_index(name='count')
daily_counts.rename(columns={'time_added': 'date'}, inplace=True)
fig = px.line(daily_counts, x='date', y='count', title='Daily Row Count Dynamics', labels={'count': 'Row Count', 'date': 'Date'})
fig.show()